name: Deployment Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            -   name: Checkout Repository   
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0          
            -   name: Setup Enviroment
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.1'
            -   name: Copy .env
                run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
            -   name: Install Packages Prod
                run: composer install --optimize-autoloader --no-dev
            -   name: Prod Config
                run: php artisan key:generate
            -   run: php artisan cache:clear
            -   run: php artisan config:clear
            -   run: php artisan config:cache
            -   run: php artisan key:generate
            -   run: php artisan config:cache
            -   run: php artisan event:cache
            -   run: php artisan route:cache
            -   run: php artisan view:cache
            
            # Here is the deployment action
            #-   name: Upload from output to a remote server via FTP
            #    uses: modern-dev/ftp-mirror@v2
            #    with:
            #        server: ${{ secrets.FTP_SERVER }}
            #        user: ${{ secrets.FTP_USER }}
            #        password: ${{ secrets.FTP_PASSWORD }}
            #        delete: "false"
            #       exlude: "vendor/ public/ .git/ .github/ .scannerwork/ "
            #-   name: FTP Interact
            #    uses: priradev/ftp-interactions@v0.2.9-beta
            #    with:
             #       # required
              #      host: ${{ secrets.FTP_SERVER }}
               #     username: ${{ secrets.FTP_USER }}
                #    password: ${{ secrets.FTP_PASSWORD }}
                 #   ftpAction: Copy
                  #  ignoreCertificateErrors: false
                    
